#!/usr/bin/env python3
"""
Script to set up environment variables for the database-backed customer service agent.
"""

import os
import platform
import sys
import logging
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Directories
ROOT_DIR = Path(__file__).parent

def create_env_file():
    """Create a .env file with environment variables for local development."""
    env_file = ROOT_DIR / ".env"
    
    # Default values
    agent_port = "8080"
    agent_host = "localhost"
    agent_base_url = f"http://{agent_host}:{agent_port}"
    
    # Create .env file content
    env_content = f"""# Environment variables for BetterSale customer service
# Generated by setup_env.py

# Agent configuration
AGENT_HOST={agent_host}
AGENT_PORT={agent_port}
AGENT_BASE_URL={agent_base_url}

# Database configuration
DATABASE_PATH={ROOT_DIR / "database" / "bettersale.db"}

# Debug mode
DEBUG=True
"""
    
    # Write to .env file
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    logger.info(f"Created .env file at {env_file}")
    
    # Print instructions for different platforms
    if platform.system() == "Windows":
        logger.info("""
To set environment variables in Windows Command Prompt:
    set AGENT_BASE_URL=http://localhost:8080

To set environment variables in Windows PowerShell:
    $env:AGENT_BASE_URL="http://localhost:8080"
""")
    else:  # Unix-like (macOS, Linux)
        logger.info("""
To set environment variables in Bash/Zsh:
    export AGENT_BASE_URL=http://localhost:8080

Or add this line to your ~/.bashrc or ~/.zshrc file:
    export AGENT_BASE_URL=http://localhost:8080
""")
    
    # Check if python-dotenv is installed
    try:
        import dotenv
        logger.info("python-dotenv is installed. Applications can load variables from .env file.")
    except ImportError:
        logger.warning("python-dotenv is not installed. Install it with: pip install python-dotenv")
    
    return env_file

def main():
    """Create environment files."""
    logger.info("Setting up environment variables...")
    
    env_file = create_env_file()
    
    logger.info(f"""
Environment setup completed!

A .env file has been created at: {env_file}

To start the application:
1. Run: python start_db_service.py

The Streamlit app will be available at http://localhost:8501
""")

if __name__ == "__main__":
    main()